#ifndef SETTINGS
#define SETTINGS
#include "raylib.h"

#define SEGMENTS_NUMBERS 20


#define MARKED_PICKED_SEGMNET_COLOR GREEN
#define DESTROYED_PICKED_SEGMNET_COLOR BLACK
#define RING_LITTLE_RADIUS 100
#define RING_BIG_RADIUS 200
#define DEFAULT_RING_SEG_SHARP 40
#define DEFAULT_RING_SEG_COLOR  BLUE
#define DEFAULT_RING_SEG_START_ANGLE 0
#define DEFAULT_RING_SEG_END_ANGLE 0
#define BALL_COLOR RED

#define DEFAULT_BALL_VELOCITY 0.05f
#define BALL_RADIUS_SCALLER_FACTOR 1.15f

#endif
