#ifndef SETTINGS
#define SETTINGS
#include "raylib.h"

#define SEGMENTS_NUMBERS 20

//ring
#define MARKED_PICKED_SEGMNET_COLOR GREEN
#define DESTROYED_PICKED_SEGMNET_COLOR BLACK
#define RING_LITTLE_RADIUS 300
#define RING_BIG_RADIUS 400
#define DEFAULT_RING_SEG_SHARP 40
#define DEFAULT_RING_SEG_COLOR  BLUE
#define DEFAULT_RING_SEG_START_ANGLE 0
#define DEFAULT_RING_SEG_END_ANGLE 0
#define BALL_COLOR RED

//ball
#define DEFAULT_BALL_VELOCITY 2.0f
#define BALL_RADIUS_SCALLER_FACTOR 1.15f

//enemy
#define ENEMY_WIDTH 100.0f
#define ENEMY_HEIGHT 50.0f
#define ENEMY_COLOR BLACK
#define ENEMY_MIN_VELOCITY 500.0f
#define ENMEY_MAX_VELOCITY 1000.0f
#define DEFAULT_ENEMIES_NUM 20
#define BASE_ENEMY_SPAWN_RATE 2.0f
#endif

